---

matrix:
  include:
    - os: linux
      sudo: false
      python: 3.6
      language: python
      dist: xenial
    - os: linux
      sudo: false
      python: 3.7
      language: python
      dist: bionic

install:
  - pip install ansible
  - pip install ansible-lint
  - pip install ansible-review
  - ansible-galaxy install --force git+https://github.com/deekayen/ansible-role-jira-software.git,${TRAVIS_COMMIT}

before_script:
  - whereis pip
  - whereis pip3
  - pip3 -V
  - ansible --version
  - ansible-review --version
  - git --version
  - python --version

script:
  - ansible-lint --exclude=/home/travis/.ansible .
  - git ls-files | grep -Ei '^[^[:punct:]].+.(yaml|yml)$' | xargs ansible-review -q
  - ansible-playbook --syntax-check -i localhost, -c local tests/test.yml
  - ansible-playbook -v --diff -i localhost, -c local tests/test.yml --extra-vars "ansible_python_interpreter=/usr/bin/python3 dhparams_bits=1024"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
