---
- name: Install jira service.
  ansible.builtin.command: /sbin/chkconfig --add jira  # noqa: command-instead-of-module
  changed_when: true

- name: Start jira.
  ansible.builtin.service:
    name: jira
    state: started
    enabled: true

- name: Restart jira.
  ansible.builtin.service:
    name: jira
    state: restarted
    enabled: true

- name: Reload nginx.
  ansible.builtin.service:
    name: nginx
    state: reloaded
    enabled: true

- name: Reload firewalld.
  ansible.builtin.service:
    name: firewalld
    state: reloaded
